<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="LambdaTest Parallel Suite" parallel="tests" thread-count="2">
	 <test name="Edge">
        <parameter name="browser" value="Firefox"/>
        <classes>
            <class name="lambdatest.com.assignment.Scenario_1"/>
            <class name="lambdatest.com.assignment.Scenario_2"/>
            <class name="lambdatest.com.assignment.Scenario_3"/>
        </classes>
    </test>	
     <test name="Win10 Chrome Test">
        <parameter name="browser" value="Chrome"/>
        <classes>
            <class name="lambdatest.com.assignment.Scenario_1"/>
            <class name="lambdatest.com.assignment.Scenario_2"/>
            <class name="lambdatest.com.assignment.Scenario_3"/>
        </classes>
    </test>
</suite>